package com.dawn.ai.agent.orchestration;

import com.dawn.ai.agent.planning.PlanStep;
import com.dawn.ai.agent.planning.TaskPlanner;
import com.dawn.ai.agent.registry.ToolRegistry;
import com.dawn.ai.agent.skill.Skill;
import com.dawn.ai.agent.skill.SkillRegistry;
import com.dawn.ai.agent.subagent.SubAgentDefinition;
import com.dawn.ai.agent.subagent.SubAgentRegistry;
import com.dawn.ai.agent.trace.AgentStep;
import com.dawn.ai.agent.trace.StepCollector;
import com.dawn.ai.agent.tools.KnowledgeSearchTool;
import com.dawn.ai.exception.AiConfigurationException;
import com.dawn.ai.exception.LLMProviderException;
import com.dawn.ai.exception.MaxStepsExceededException;
import com.dawn.ai.exception.PlanGenerationException;
import com.dawn.ai.memory.MemoryManager;
import com.dawn.ai.memory.UserProfileService;
import com.dawn.ai.service.MemoryService;
import com.dawn.ai.sse.ChatStreamEvent;
import com.dawn.ai.sse.StreamSinkHolder;
import io.micrometer.core.instrument.Counter;
import io.micrometer.core.instrument.DistributionSummary;
import io.micrometer.core.instrument.MeterRegistry;
import io.micrometer.core.instrument.Timer;
import jakarta.annotation.PostConstruct;
import lombok.extern.slf4j.Slf4j;
import org.springframework.ai.chat.client.ChatClient;
import org.springframework.ai.chat.messages.AssistantMessage;
import org.springframework.ai.chat.messages.Message;
import org.springframework.ai.chat.messages.UserMessage;
import org.springframework.ai.chat.model.ChatResponse;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Service;

import java.util.ArrayList;
import java.util.Collection;
import java.util.List;
import java.util.function.BooleanSupplier;
import java.util.function.Consumer;
import java.util.Map;
import java.util.stream.Stream;

/**
 * Agent Orchestrator — orchestrates the full ReAct loop with planning and step tracing.
 *
 * Flow per request:
 *  1. StepCollector.init()         — reset thread-local state
 *  2. TaskPlanner.plan()           — pre-execution planning via a separate LLM call (optional)
 *  3. Build system prompt          — base prompt + plan summary + max-steps instruction
 *  4. chatClient + .toolNames()    — Spring AI handles the tool-calling loop
 *  5. ToolExecutionAspect (AOP)    — intercepts each tool call, records it automatically
 *  6. StepCollector.collect()      — gather all recorded steps
 *  7. Persist to memory            — save turn to Redis
 *  8. StepCollector.clear()        — prevent ThreadLocal memory leak
 */
@Slf4j
@Service
public class AgentOrchestrator {

    private final ChatClient chatClient;
    private final MemoryService memoryService;
    private final MemoryManager memoryManager;
    private final TaskPlanner taskPlanner;
    private final ToolRegistry toolRegistry;
    private final MeterRegistry meterRegistry;
    private final UserProfileService userProfileService;
    private final SkillRegistry skillRegistry;
    private final SubAgentRegistry subAgentRegistry;

    public AgentOrchestrator(ChatClient chatClient,
                              MemoryService memoryService,
                              MemoryManager memoryManager,
                              TaskPlanner taskPlanner,
                              ToolRegistry toolRegistry,
                              MeterRegistry meterRegistry,
                              UserProfileService userProfileService,
                              SkillRegistry skillRegistry,
                              SubAgentRegistry subAgentRegistry) {
        this.chatClient = chatClient;
        this.memoryService = memoryService;
        this.memoryManager = memoryManager;
        this.taskPlanner = taskPlanner;
        this.toolRegistry = toolRegistry;
        this.meterRegistry = meterRegistry;
        this.userProfileService = userProfileService;
        this.skillRegistry = skillRegistry;
        this.subAgentRegistry = subAgentRegistry;
    }

    @Value("${app.ai.system-prompt:You are a helpful AI assistant.}")
    private String baseSystemPrompt;

    @Value("${app.ai.react.max-steps:10}")
    private int maxSteps;

    @Value("${app.ai.react.plan-enabled:true}")
    private boolean planEnabled;

    @Value("${spring.ai.openai.chat.options.model:qwen-plus}")
    private String model;

    @Value("${app.ai.subagent.max-dispatches-per-session:3}")
    private int maxSubAgentDispatches;

    private Counter inputTokenCounter;
    private Counter outputTokenCounter;
    private DistributionSummary ragCallsSummary;

    @PostConstruct
    void initMetrics() {
        inputTokenCounter = Counter.builder("ai.token.input")
                .description("Total input (prompt) tokens consumed by the LLM")
                .register(meterRegistry);
        outputTokenCounter = Counter.builder("ai.token.output")
                .description("Total output (completion) tokens generated by the LLM")
                .register(meterRegistry);
        ragCallsSummary = DistributionSummary.builder("ai.rag.calls_per_session")
                .description("Number of knowledgeSearchTool calls per agent session")
                .register(meterRegistry);
    }

    public AgentResult chat(String sessionId, String userMessage, String topicId) {
        return Timer.builder("ai.agent.chat.duration")
                .tag("session", "anonymous")
                .register(meterRegistry)
                .record(() -> doChat(sessionId, userMessage, topicId));
    }

    private AgentResult doChat(String sessionId, String userMessage, String topicId) {
        StepCollector.init(maxSteps);
        try {
            TaskPlanner.PlannerResult plannerResult = resolvePlan(userMessage);
            List<PlanStep> plan = plannerResult.steps();

            String systemPrompt = buildSystemPrompt(plan, sessionId, topicId);

            // 添加历史对话到上下文
            List<Message> history = buildHistory(sessionId);

            ChatResponse chatResponse = callWithRetry(() -> chatClient.prompt()
                    .system(systemPrompt)
                    .messages(history)
                    .user(userMessage)
                    .toolNames(toolRegistry.getNames())
                    .call()
                    .chatResponse());

            String response = chatResponse.getResult().getOutput().getText();
            recordTokenUsage(chatResponse);

            List<AgentStep> steps = StepCollector.collect();
            recordRagMetrics(steps);

            memoryService.addMessage(sessionId, sessionId, "user", userMessage);
            memoryService.addMessage(sessionId, sessionId, "assistant", response);

            log.info("[AgentOrchestrator] session={}, planSteps={}, toolCalls={}, userMsg={}",
                    sessionId, plan.size(), steps.size(),
                    userMessage.substring(0, Math.min(50, userMessage.length())));

            return new AgentResult(response, steps, plan);
        } catch(MaxStepsExceededException maxStepsExceededException) {
            throw maxStepsExceededException;
        } catch (Exception e) {
            log.error("call LLM met error: {}", e.getMessage(), e);
            throw new LLMProviderException("call LLM met error: " + e.getMessage());
        }
        finally {
            StepCollector.clear();
        }
    }

    private <T> T callWithRetry(java.util.function.Supplier<T> call) {
        int maxRetries = 3;
        long baseDelay = 5000; // 5s
        for (int attempt = 0; attempt <= maxRetries; attempt++) {
            try {
                return call.get();
            } catch (Exception e) {
                boolean is429 = e.getMessage() != null && e.getMessage().contains("429");
                if (is429 && attempt < maxRetries) {
                    long delay = baseDelay * (1L << attempt); // exponential: 5s, 10s, 20s
                    log.warn("[AgentOrchestrator] 429 rate limited, retrying in {}ms (attempt {}/{})", delay, attempt + 1, maxRetries);
                    try { Thread.sleep(delay); } catch (InterruptedException ie) { Thread.currentThread().interrupt(); throw e; }
                } else {
                    throw e;
                }
            }
        }
        throw new IllegalStateException("unreachable");
    }

    private TaskPlanner.PlannerResult resolvePlan(String userMessage) {
        if (!planEnabled) {
            return TaskPlanner.PlannerResult.empty();
        }

        try {
            return taskPlanner.plan(userMessage, toolRegistry.getDescriptions());
        } catch (PlanGenerationException exception) {
            log.warn("[AgentOrchestrator] Planner failed, falling back to direct execution. userMsg={}, reason={}",
                    userMessage.substring(0, Math.min(50, userMessage.length())),
                    exception.getMessage());
            return TaskPlanner.PlannerResult.empty();
        }
    }

    /**
     * Streaming variant of {@link #chat}.
     *
     * <p>Publishes SSE events to {@code sink} in this order:
     * {@code connected → plan_thinking* → plan? → thinking* → step* → token* → done | error}
     * (see {@link ChatStreamEvent} for the canonical sequence).
     *
     * <p>This method always returns normally; errors are surfaced via an {@code error} event.
     * The caller must run this on a dedicated non-servlet thread and complete the
     * {@code SseEmitter} after this method returns.
     *
     * @param isCancelled supplier checked before each streamed chunk; when {@code true} the
     *                    Reactor pipeline is torn down early (client disconnected).
     */
    public void streamChat(String sessionId, String userMessage, String topicId,
                           Consumer<ChatStreamEvent> sink, BooleanSupplier isCancelled) {
        long start = System.currentTimeMillis();
        StringBuilder answer = new StringBuilder();
        StringBuilder thinkingBuffer = new StringBuilder();
        StringBuilder planThinkingBuffer = new StringBuilder();

        Consumer<AgentStep> stepEventPublisher = step -> sink.accept(ChatStreamEvent.step(sessionId, step));
        StepCollector.init(maxSteps, stepEventPublisher);
        StreamSinkHolder.set(sink);
        try {
            TaskPlanner.PlannerResult plannerResult = resolvePlan(userMessage);
            List<PlanStep> plan = plannerResult.steps();

            String planReasoning = plannerResult.reasoningContent();
            if (planReasoning != null && !planReasoning.isBlank()) {
                planThinkingBuffer.append(planReasoning);
                sink.accept(ChatStreamEvent.planThinking(sessionId, planReasoning, planThinkingBuffer.length()));
            }

            if (!plan.isEmpty()) {
                sink.accept(ChatStreamEvent.plan(sessionId, plan, formatPlanSummary(plan)));
            }

            // 系统提示词 + 用户画像 + 相关记忆（top-k）
            // skills meta data + subagent description + plan description
            String systemPrompt = buildSystemPrompt(plan, sessionId, topicId);

            // 添加历史对话到上下文
            List<Message> history = buildHistory(sessionId);

                log.info("[AI STREAM] --> session={}, planSteps={}, tools={}, historyMessages={}, userMsg={}",
                        sessionId, plan.size(), toolRegistry.getNames().length, history.size(),
                    userMessage.substring(0, Math.min(80, userMessage.length())));

            chatClient.prompt()
                    .system(systemPrompt)
                    .messages(history)
                    .user(userMessage)
                    .toolNames(toolRegistry.getNames())
                    .stream()
                    .chatResponse()
                    .contextCapture() // 在当前 pipeline 订阅点主动把所有已注册 ThreadLocal 快照进 Reactor Context
                    .takeWhile(chunk -> !isCancelled.getAsBoolean())
                    .doOnNext(chunk -> {
                        String reasoning = extractReasoning(chunk);
                        if (reasoning != null && !reasoning.isBlank()) {
                            thinkingBuffer.append(reasoning);
                            sink.accept(ChatStreamEvent.thinking(sessionId, reasoning, thinkingBuffer.length()));
                        }
                        String delta = extractDelta(chunk);
                        if (delta != null && !delta.isBlank()) {
                            answer.append(delta);
                            sink.accept(ChatStreamEvent.token(sessionId, delta, answer.length()));
                        }
                        if ((reasoning != null && !reasoning.isBlank()) || (delta != null && !delta.isBlank())) {
                            log.trace("[AI STREAM] chunk session={}, reasoningChars={}, answerChars={}, deltaChars={}",
                                    sessionId,
                                    reasoning != null ? reasoning.length() : 0,
                                    answer.length(),
                                    delta != null ? delta.length() : 0);
                        }
                    })
                    .blockLast();

            if (isCancelled.getAsBoolean()) {
                log.info("[AgentOrchestrator] stream cancelled by client, session={}", sessionId);
                return;
            }

            List<AgentStep> steps = StepCollector.collect();
            recordRagMetrics(steps);

            memoryService.addMessage(sessionId, sessionId, "user", userMessage);
            memoryService.addMessage(sessionId, sessionId, "assistant", answer.toString());

            log.info("[AgentOrchestrator] stream session={}, planSteps={}, toolCalls={}, tokens={}",
                    sessionId, plan.size(), steps.size(), answer.length());

            sink.accept(ChatStreamEvent.done(
                    sessionId, answer.toString(), steps, plan,
                    System.currentTimeMillis() - start, model));

        } catch (Exception e) {
            Throwable cause = e.getCause() != null ? e.getCause() : e;
            String code;
            if (cause instanceof MaxStepsExceededException) {
                code = "MAX_STEPS_EXCEEDED";
            } else if (cause instanceof AiConfigurationException) {
                code = "AI_NOT_CONFIGURED";
            } else {
                code = "INTERNAL_ERROR";
                log.error("[AgentOrchestrator] streamChat error, session={}", sessionId, e);
            }
            sink.accept(ChatStreamEvent.error(sessionId, code, cause.getMessage()));
        } finally {
            StepCollector.clear();
            StreamSinkHolder.clear();
        }
    }

    private String extractDelta(ChatResponse chunk) {
        if (chunk == null || chunk.getResult() == null) return null;
        var output = chunk.getResult().getOutput();
        if (output == null) return null;
        return output.getText();
    }

    private String extractReasoning(ChatResponse chunk) {
        if (chunk == null || chunk.getResult() == null) return null;

        String fromGeneration = chunk.getResult().getMetadata().get("reasoningContent");
        if (fromGeneration != null && !fromGeneration.isBlank()) {
            return fromGeneration;
        }

        var output = chunk.getResult().getOutput();
        if (output == null || output.getMetadata() == null) {
            return null;
        }

        Object fromMessage = output.getMetadata().get("reasoningContent");
        return fromMessage instanceof String reasoning && !reasoning.isBlank() ? reasoning : null;
    }

    private void recordRagMetrics(List<AgentStep> steps) {
        long ragCalls = steps.stream()
                .filter(s -> KnowledgeSearchTool.class.getSimpleName().equals(s.toolName()))
                .count();
        ragCallsSummary.record(ragCalls);
    }

    private String formatPlanSummary(List<PlanStep> plan) {
        if (plan == null || plan.isEmpty()) return "";
        StringBuilder sb = new StringBuilder();
        for (int i = 0; i < plan.size(); i++) {
            if (i > 0) sb.append(" → ");
            sb.append("步骤").append(plan.get(i).step()).append(": ").append(plan.get(i).action());
        }
        return sb.toString();
    }


    private void recordTokenUsage(ChatResponse chatResponse) {
        org.springframework.ai.chat.metadata.Usage usage = chatResponse.getMetadata().getUsage();
        if (usage == null) {
            return;
        }

        Integer inputTokens = usage.getPromptTokens();
        Integer outputTokens = usage.getCompletionTokens();
        if (inputTokens != null && inputTokens > 0) {
            inputTokenCounter.increment(inputTokens);
        }
        if (outputTokens != null && outputTokens > 0) {
            outputTokenCounter.increment(outputTokens);
        }
        log.debug("[AgentOrchestrator] token usage: input={}, output={}", inputTokens, outputTokens);
    }

    private List<Message> buildHistory(String sessionId) {
        List<Map<String, String>> rawHistory = memoryService.getHistory(sessionId);
        List<Message> messages = new ArrayList<>();
        for (Map<String, String> entry : rawHistory) {
            String role = entry.get("role");
            String content = entry.get("content");
            if ("user".equals(role)) {
                messages.add(new UserMessage(content));
            } else if ("assistant".equals(role)) {
                messages.add(new AssistantMessage(content));
            }
        }
        return messages;
    }

    private String formatPlan(List<PlanStep> plan) {
        if (plan.isEmpty()) {
            return "";
        }
        StringBuilder sb = new StringBuilder("\n\n【执行计划】\n");
        for (PlanStep step : plan) {
            // 过滤掉 "finish" 步骤 - 这只是规划器的内部标记，不应暴露给执行阶段的LLM
            if ("finish".equals(step.action())) {
                continue;
            }
            sb.append(step.step())
                    .append(". [").append(step.action()).append("] ")
                    .append(step.reason()).append("\n");
        }
        return sb.toString();
    }

    /**
     * Returns a mandatory enforcement directive when a non-empty plan exists.
     * Without this, the LLM may answer from training knowledge and skip tool calls entirely.
     */
    /**
     * Builds the system prompt shared by both sync and stream paths.
     * Includes the execution plan, plan-enforcement directive, and max-steps constraint.
     */
    private String buildSystemPrompt(List<PlanStep> plan, String sessionId, String topicId) {
        String profileSection = userProfileService.formatForSystemPrompt(sessionId); // 用户画像
        String memorySection = formatMemories(sessionId); // 相关记忆，top-k
        String topicSection = (topicId != null && !topicId.isBlank())
                ? String.format("%n%n【研究主题】你当前在帮助用户研究主题：%s。" +
                  "调用 KnowledgeSearchTool 时，topicId 参数必须使用 \"%s\"。", topicId, topicId)
                : "";
        return baseSystemPrompt
                + profileSection
                + memorySection
                + topicSection
                + formatSkills()
                + formatSubAgents()
                + formatPlan(plan)
                + formatPlanEnforcement(plan)
                + String.format("%n请在回复中简短说明每次工具调用的原因。最多调用工具 %d 次。", maxSteps);
    }

    /**
     * 列出当前可派发的 sub-agent 类型，并给出判断准则。
     * 与 {@link #formatSkills()} 同源（progressive disclosure / 注册表驱动），
     * 在 {@link SubAgentRegistry} 为空时返回空串，不污染 prompt。
     */
    private String formatSubAgents() {
        if (subAgentRegistry.isEmpty()) {
            return "";
        }
        StringBuilder sb = new StringBuilder("\n\n## 可派发的子 Agent (Sub-Agent)\n")
                .append("调用 `dispatchSubAgentTool(subagentType, taskDescription)` 把深度调研/长文档分析这类'重活'派给隔离上下文的子 Agent。\n")
                .append("\n判断准则：\n")
                .append("- ✅ 适合派：需要多轮检索 / 多角度分析 / 长文档综合，单 Agent 上下文会被噪声淹没\n")
                .append("- ❌ 不要派：单次 knowledge_search 1-2 次能搞定的简单问题；用 weather/calculator 等专用工具就够的\n")
                .append("\n约束：单次对话最多派 ").append(maxSubAgentDispatches).append(" 次；")
                .append("taskDescription 必须自包含（子 Agent 看不到对话历史）；子 Agent 返回 status=PARTIAL_SUCCESS 时基于已有信息判断是否够用。\n\n")
                .append("可用类型：\n");
        for (SubAgentDefinition def : subAgentRegistry.list()) {
            sb.append("- **").append(def.type()).append("**：");
            String firstLine = def.systemPrompt().lines().findFirst().orElse(def.type());
            sb.append(firstLine).append("\n");
        }
        return sb.toString();
    }

    /**
     * 列出所有可用 Skill 的 name + description（progressive disclosure 第一层）。
     * 模型据此判断是否调用 {@code load_skill} 加载某个 skill 的完整指令。
     * 若无可用 skill 则返回空串，不污染 prompt。
     */
    private String formatSkills() {
        Collection<Skill> all = skillRegistry.list();
        if (all.isEmpty()) {
            return "";
        }
        StringBuilder sb = new StringBuilder("\n\n## 可用 Skills\n")
                .append("按需调用 `load_skill(name)` 加载完整指令；")
                .append("需要 skill 的内嵌资源时调用 `read_skill_resource(skill, path)`。\n\n");
        for (Skill s : all) {
            sb.append("- **").append(s.manifest().name()).append("**: ")
              .append(s.manifest().description()).append("\n");
        }
        return sb.toString();
    }

    private String formatMemories(String userId) {
        try {
            List<MemoryManager.MemorySearchResult> memories = memoryManager.search(userId, "用户偏好和习惯", 5);
            if (memories.isEmpty()) {
                return "";
            }
            StringBuilder sb = new StringBuilder("\n\n【相关记忆】\n");
            for (MemoryManager.MemorySearchResult mem : memories) {
                sb.append("- ").append(mem.content()).append("\n");
            }
            return sb.toString();
        } catch (Exception e) {
            log.debug("[AgentOrchestrator] Failed to fetch memories for user={}: {}", userId, e.getMessage());
            return "";
        }
    }

    private String formatPlanEnforcement(List<PlanStep> plan) {
        if (plan.isEmpty()) {
            return "";
        }
        return "\n\n【强制约束】你必须严格按照上方【执行计划】依次调用对应工具，" +
               "不得依赖自身训练知识直接回答。完成所有工具调用后，再基于结果生成最终答案。";
    }
}
