package com.dawn.ai.agent.orchestration;

import com.dawn.ai.agent.planning.PlanStep;
import com.dawn.ai.agent.planning.TaskPlanner;
import com.dawn.ai.agent.registry.ToolRegistry;
import com.dawn.ai.agent.trace.AgentStep;
import com.dawn.ai.agent.trace.StepCollector;
import com.dawn.ai.agent.tools.KnowledgeSearchTool;
import com.dawn.ai.exception.AiConfigurationException;
import com.dawn.ai.exception.LLMProviderException;
import com.dawn.ai.exception.MaxStepsExceededException;
import com.dawn.ai.exception.PlanGenerationException;
import com.dawn.ai.service.MemoryService;
import com.dawn.ai.sse.ChatStreamEvent;
import io.micrometer.core.instrument.Counter;
import io.micrometer.core.instrument.DistributionSummary;
import io.micrometer.core.instrument.MeterRegistry;
import io.micrometer.core.instrument.Timer;
import jakarta.annotation.PostConstruct;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.ai.chat.client.ChatClient;
import org.springframework.ai.chat.messages.AssistantMessage;
import org.springframework.ai.chat.messages.Message;
import org.springframework.ai.chat.messages.UserMessage;
import org.springframework.ai.chat.model.ChatResponse;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Service;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.function.Consumer;
import java.util.Map;

/**
 * Agent Orchestrator — orchestrates the full ReAct loop with planning and step tracing.
 *
 * Flow per request:
 *  1. StepCollector.init()         — reset thread-local state
 *  2. TaskPlanner.plan()           — pre-execution planning via a separate LLM call (optional)
 *  3. Build system prompt          — base prompt + plan summary + max-steps instruction
 *  4. chatClient + .toolNames()    — Spring AI handles the tool-calling loop
 *  5. ToolExecutionAspect (AOP)    — intercepts each tool call, records it automatically
 *  6. StepCollector.collect()      — gather all recorded steps
 *  7. Persist to memory            — save turn to Redis
 *  8. StepCollector.clear()        — prevent ThreadLocal memory leak
 */
@Slf4j
@Service
@RequiredArgsConstructor
public class AgentOrchestrator {

    private final ChatClient chatClient;
    private final MemoryService memoryService;
    private final TaskPlanner taskPlanner;
    private final ToolRegistry toolRegistry;
    private final MeterRegistry meterRegistry;

    @Value("${app.ai.system-prompt:You are a helpful AI assistant.}")
    private String baseSystemPrompt;

    @Value("${app.ai.react.max-steps:10}")
    private int maxSteps;

    @Value("${app.ai.react.plan-enabled:true}")
    private boolean planEnabled;

    @Value("${spring.ai.openai.chat.options.model:qwen-plus}")
    private String model;

    private Counter inputTokenCounter;
    private Counter outputTokenCounter;
    private DistributionSummary ragCallsSummary;

    @PostConstruct
    void initMetrics() {
        inputTokenCounter = Counter.builder("ai.token.input")
                .description("Total input (prompt) tokens consumed by the LLM")
                .register(meterRegistry);
        outputTokenCounter = Counter.builder("ai.token.output")
                .description("Total output (completion) tokens generated by the LLM")
                .register(meterRegistry);
        ragCallsSummary = DistributionSummary.builder("ai.rag.calls_per_session")
                .description("Number of knowledgeSearchTool calls per agent session")
                .register(meterRegistry);
    }

    public AgentResult chat(String sessionId, String userMessage) {
        return Timer.builder("ai.agent.chat.duration")
                .tag("session", "anonymous")
                .register(meterRegistry)
                .record(() -> doChat(sessionId, userMessage));
    }

    private AgentResult doChat(String sessionId, String userMessage) {
        StepCollector.init(maxSteps);
        try {
            List<PlanStep> plan = resolvePlan(userMessage);

            String systemPrompt = baseSystemPrompt
                    + formatPlan(plan)
                    + String.format("%n请在回复中简短说明每次工具调用的原因。最多调用工具 %d 次。", maxSteps);

            // 添加历史对话到上下文
            List<Message> history = buildHistory(sessionId);

            ChatResponse chatResponse = chatClient.prompt()
                    .system(systemPrompt)
                    .messages(history)
                    .user(userMessage)
                    .toolNames(toolRegistry.getNames())
                    .call()
                    .chatResponse();

            String response = chatResponse.getResult().getOutput().getText();
            recordTokenUsage(chatResponse);

            List<AgentStep> steps = StepCollector.collect();
            recordRagMetrics(steps);

            memoryService.addMessage(sessionId, "user", userMessage);
            memoryService.addMessage(sessionId, "assistant", response);

            log.info("[AgentOrchestrator] session={}, planSteps={}, toolCalls={}, userMsg={}",
                    sessionId, plan.size(), steps.size(),
                    userMessage.substring(0, Math.min(50, userMessage.length())));

            return new AgentResult(response, steps, plan);
        } catch(MaxStepsExceededException maxStepsExceededException) {
            throw maxStepsExceededException;
        } catch (Exception e) {
            log.error("call LLM met error: {}", e.getMessage(), e);
            throw new LLMProviderException("call LLM met error: " + e.getMessage());
        }
        finally {
            StepCollector.clear();
        }
    }

    private List<PlanStep> resolvePlan(String userMessage) {
        if (!planEnabled) {
            return Collections.emptyList();
        }

        try {
            return taskPlanner.plan(userMessage, toolRegistry.getDescriptions());
        } catch (PlanGenerationException exception) {
            log.warn("[AgentOrchestrator] Planner failed, falling back to direct execution. userMsg={}, reason={}",
                    userMessage.substring(0, Math.min(50, userMessage.length())),
                    exception.getMessage());
            return Collections.emptyList();
        }
    }

    /**
     * Streaming variant of {@link #chat}.
     *
     * <p>Publishes SSE events to {@code sink} in this order:
     * {@code plan → step* → token* → done | error}.
     *
     * <p>This method always returns normally; errors are surfaced via an {@code error} event.
     * The caller must run this on a dedicated non-servlet thread and complete the
     * {@code SseEmitter} after this method returns.
     *
     * <p>Note: {@code step} events rely on {@link StepCollector}'s ThreadLocal listener.
     * They are delivered if Spring AI executes tools on the same thread chain as
     * {@code blockLast()}.  Even if step delivery is not guaranteed in all provider
     * implementations, {@code plan}, {@code token}, and {@code done} events are always
     * reliable.
     */
    public void streamChat(String sessionId, String userMessage, Consumer<ChatStreamEvent> sink) {
        long start = System.currentTimeMillis();
        StringBuilder answer = new StringBuilder();

        StepCollector.init(maxSteps,
                step -> sink.accept(ChatStreamEvent.step(sessionId, step)));
        try {
            List<PlanStep> plan = resolvePlan(userMessage);

            if (!plan.isEmpty()) {
                sink.accept(ChatStreamEvent.plan(sessionId, plan, formatPlanSummary(plan)));
            }

            String systemPrompt = baseSystemPrompt
                    + formatPlan(plan)
                    + String.format("%n请在回复中简短说明每次工具调用的原因。最多调用工具 %d 次。", maxSteps);

            List<Message> history = buildHistory(sessionId);

            chatClient.prompt()
                    .system(systemPrompt)
                    .messages(history)
                    .user(userMessage)
                    .toolNames(toolRegistry.getNames())
                    .stream()
                    .chatResponse()
                    .doOnNext(chunk -> {
                        String delta = extractDelta(chunk);
                        if (delta != null && !delta.isBlank()) {
                            answer.append(delta);
                            sink.accept(ChatStreamEvent.token(sessionId, delta, answer.length()));
                        }
                    })
                    .blockLast();

            List<AgentStep> steps = StepCollector.collect();
            recordRagMetrics(steps);

            memoryService.addMessage(sessionId, "user", userMessage);
            memoryService.addMessage(sessionId, "assistant", answer.toString());

            log.info("[AgentOrchestrator] stream session={}, planSteps={}, toolCalls={}, tokens={}",
                    sessionId, plan.size(), steps.size(), answer.length());

            sink.accept(ChatStreamEvent.done(
                    sessionId, answer.toString(), steps, plan,
                    System.currentTimeMillis() - start, model));

        } catch (Exception e) {
            Throwable cause = e.getCause() != null ? e.getCause() : e;
            String code;
            if (cause instanceof MaxStepsExceededException) {
                code = "MAX_STEPS_EXCEEDED";
            } else if (cause instanceof AiConfigurationException) {
                code = "AI_NOT_CONFIGURED";
            } else {
                code = "INTERNAL_ERROR";
                log.error("[AgentOrchestrator] streamChat error, session={}", sessionId, e);
            }
            sink.accept(ChatStreamEvent.error(sessionId, code, cause.getMessage()));
        } finally {
            StepCollector.clear();
        }
    }

    private String extractDelta(ChatResponse chunk) {
        if (chunk == null || chunk.getResult() == null) return null;
        var output = chunk.getResult().getOutput();
        if (output == null) return null;
        return output.getText();
    }

    private void recordRagMetrics(List<AgentStep> steps) {
        long ragCalls = steps.stream()
                .filter(s -> KnowledgeSearchTool.class.getSimpleName().equals(s.toolName()))
                .count();
        ragCallsSummary.record(ragCalls);
    }

    private String formatPlanSummary(List<PlanStep> plan) {
        if (plan == null || plan.isEmpty()) return "";
        StringBuilder sb = new StringBuilder();
        for (int i = 0; i < plan.size(); i++) {
            if (i > 0) sb.append(" → ");
            sb.append("步骤").append(plan.get(i).step()).append(": ").append(plan.get(i).action());
        }
        return sb.toString();
    }


    private void recordTokenUsage(ChatResponse chatResponse) {
        org.springframework.ai.chat.metadata.Usage usage = chatResponse.getMetadata().getUsage();
        if (usage == null) {
            return;
        }

        Integer inputTokens = usage.getPromptTokens();
        Integer outputTokens = usage.getCompletionTokens();
        if (inputTokens != null && inputTokens > 0) {
            inputTokenCounter.increment(inputTokens);
        }
        if (outputTokens != null && outputTokens > 0) {
            outputTokenCounter.increment(outputTokens);
        }
        log.debug("[AgentOrchestrator] token usage: input={}, output={}", inputTokens, outputTokens);
    }

    private List<Message> buildHistory(String sessionId) {
        List<Map<String, String>> rawHistory = memoryService.getHistory(sessionId);
        List<Message> messages = new ArrayList<>();
        for (Map<String, String> entry : rawHistory) {
            String role = entry.get("role");
            String content = entry.get("content");
            if ("user".equals(role)) {
                messages.add(new UserMessage(content));
            } else if ("assistant".equals(role)) {
                messages.add(new AssistantMessage(content));
            }
        }
        return messages;
    }

    private String formatPlan(List<PlanStep> plan) {
        if (plan.isEmpty()) {
            return "";
        }
        StringBuilder sb = new StringBuilder("\n\n【执行计划】\n");
        for (PlanStep step : plan) {
            sb.append(step.step())
                    .append(". [").append(step.action()).append("] ")
                    .append(step.reason()).append("\n");
        }
        return sb.toString();
    }
}
