package com.dawn.ai.agent;

import com.dawn.ai.agent.plan.PlanStep;
import com.dawn.ai.agent.plan.TaskPlanner;
import com.dawn.ai.exception.LLMProviderException;
import com.dawn.ai.exception.MaxStepsExceededException;
import com.dawn.ai.exception.PlanGenerationException;
import com.dawn.ai.service.MemoryService;
import io.micrometer.core.instrument.Counter;
import io.micrometer.core.instrument.MeterRegistry;
import io.micrometer.core.instrument.Timer;
import jakarta.annotation.PostConstruct;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.ai.chat.client.ChatClient;
import org.springframework.ai.chat.messages.AssistantMessage;
import org.springframework.ai.chat.messages.Message;
import org.springframework.ai.chat.messages.UserMessage;
import org.springframework.ai.chat.model.ChatResponse;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Service;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.Map;

/**
 * Agent Orchestrator — orchestrates the full ReAct loop with planning and step tracing.
 *
 * Flow per request:
 *  1. StepCollector.init()         — reset thread-local state
 *  2. TaskPlanner.plan()           — pre-execution planning via a separate LLM call (optional)
 *  3. Build system prompt          — base prompt + plan summary + max-steps instruction
 *  4. chatClient + .toolNames()    — Spring AI handles the tool-calling loop
 *  5. ToolExecutionAspect (AOP)    — intercepts each tool call, records it automatically
 *  6. StepCollector.collect()      — gather all recorded steps
 *  7. Persist to memory            — save turn to Redis
 *  8. StepCollector.clear()        — prevent ThreadLocal memory leak
 */
@Slf4j
@Service
@RequiredArgsConstructor
public class AgentOrchestrator {

    private final ChatClient chatClient;
    private final MemoryService memoryService;
    private final TaskPlanner taskPlanner;
    private final ToolRegistry toolRegistry;
    private final MeterRegistry meterRegistry;

    @Value("${app.ai.system-prompt:You are a helpful AI assistant.}")
    private String baseSystemPrompt;

    @Value("${app.ai.react.max-steps:10}")
    private int maxSteps;

    @Value("${app.ai.react.plan-enabled:true}")
    private boolean planEnabled;

    private Counter inputTokenCounter;
    private Counter outputTokenCounter;

    @PostConstruct
    void initMetrics() {
        inputTokenCounter = Counter.builder("ai.token.input")
                .description("Total input (prompt) tokens consumed by the LLM")
                .register(meterRegistry);
        outputTokenCounter = Counter.builder("ai.token.output")
                .description("Total output (completion) tokens generated by the LLM")
                .register(meterRegistry);
    }

    public AgentResult chat(String sessionId, String userMessage) {
        return Timer.builder("ai.agent.chat.duration")
                .tag("session", "anonymous")
                .register(meterRegistry)
                .record(() -> doChat(sessionId, userMessage));
    }

    private AgentResult doChat(String sessionId, String userMessage) {
        StepCollector.init(maxSteps);
        try {
            List<PlanStep> plan = resolvePlan(userMessage);

            String systemPrompt = baseSystemPrompt
                    + formatPlan(plan)
                    + String.format("%n请在回复中简短说明每次工具调用的原因。最多调用工具 %d 次。", maxSteps);

            List<Message> history = buildHistory(sessionId);

            ChatResponse chatResponse = chatClient.prompt()
                    .system(systemPrompt)
                    .messages(history)
                    .user(userMessage)
                    .toolNames(toolRegistry.getNames())
                    .call()
                    .chatResponse();

            String response = chatResponse.getResult().getOutput().getText();
            recordTokenUsage(chatResponse);

            List<AgentStep> steps = StepCollector.collect();

            memoryService.addMessage(sessionId, "user", userMessage);
            memoryService.addMessage(sessionId, "assistant", response);

            log.info("[AgentOrchestrator] session={}, planSteps={}, toolCalls={}, userMsg={}",
                    sessionId, plan.size(), steps.size(),
                    userMessage.substring(0, Math.min(50, userMessage.length())));

            return new AgentResult(response, steps, plan);
        } catch(MaxStepsExceededException maxStepsExceededException) {
            throw maxStepsExceededException;
        } catch (Exception e) {
            log.error("call LLM met error: {}", e.getMessage(), e);
            throw new LLMProviderException("call LLM met error: " + e.getMessage());
        }
        finally {
            StepCollector.clear();
        }
    }

    private List<PlanStep> resolvePlan(String userMessage) {
        if (!planEnabled) {
            return Collections.emptyList();
        }

        try {
            return taskPlanner.plan(userMessage, toolRegistry.getDescriptions());
        } catch (PlanGenerationException exception) {
            log.warn("[AgentOrchestrator] Planner failed, falling back to direct execution. userMsg={}, reason={}",
                    userMessage.substring(0, Math.min(50, userMessage.length())),
                    exception.getMessage());
            return Collections.emptyList();
        }
    }

    private void recordTokenUsage(ChatResponse chatResponse) {
        org.springframework.ai.chat.metadata.Usage usage = chatResponse.getMetadata().getUsage();
        if (usage == null) {
            return;
        }

        Integer inputTokens = usage.getPromptTokens();
        Integer outputTokens = usage.getCompletionTokens();
        if (inputTokens != null && inputTokens > 0) {
            inputTokenCounter.increment(inputTokens);
        }
        if (outputTokens != null && outputTokens > 0) {
            outputTokenCounter.increment(outputTokens);
        }
        log.debug("[AgentOrchestrator] token usage: input={}, output={}", inputTokens, outputTokens);
    }

    private List<Message> buildHistory(String sessionId) {
        List<Map<String, String>> rawHistory = memoryService.getHistory(sessionId);
        List<Message> messages = new ArrayList<>();
        for (Map<String, String> entry : rawHistory) {
            String role = entry.get("role");
            String content = entry.get("content");
            if ("user".equals(role)) {
                messages.add(new UserMessage(content));
            } else if ("assistant".equals(role)) {
                messages.add(new AssistantMessage(content));
            }
        }
        return messages;
    }

    private String formatPlan(List<PlanStep> plan) {
        if (plan.isEmpty()) {
            return "";
        }
        StringBuilder sb = new StringBuilder("\n\n【执行计划】\n");
        for (PlanStep step : plan) {
            sb.append(step.step())
                    .append(". [").append(step.action()).append("] ")
                    .append(step.reason()).append("\n");
        }
        return sb.toString();
    }
}
